<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>d94da21a-00df-4802-a309-c18641945df3</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ical.Net" Version="5.2.3" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

</Project>
